frogblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('froggy.urls', namespace='froggy')),
]

froggy/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^topics/$', views.topics, name='topics'),
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
	url(r'^new_topic/$', views.new_topic, name='new_topic'),
	url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
	url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
	url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

	url(r'^logout/$', views.logout_view, name='logout'),

	url(r'^register/$', views.register, name='register'),
]

froggy/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
	text = models.CharField(max_length=150)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User)
	def __str__(self):
		return self.text

class Entry(models.Model):
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		if len(self.text) > 50:
			return self.text[:50] + "..."
		else:
			return self.text

users/models.py
from django.db import models

# Create your models here.

froggy/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

froggy/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def home(request):
	return render(request, 'froggy/home.html')

@login_required
def topics(request):
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics':topics}
	return render(request, 'froggy/topics.html', context)

@login_required
def topic(request, topic_id):
	topic = Topic.objects.get(id=topic_id)
	if topic.owner != request.user:
		raise Http404
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic':topic, 'entries':entries}
	return render(request, 'froggy/topic.html', context)

@login_required
def new_topic(request):
	if request.method != 'POST':
		form = TopicForm()
	else:
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('froggy:topics'))

	context = {'form': form}
	return render(request, 'froggy/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form = EntryForm()
	else:
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('froggy:topic', args=[topic_id]))

	context = {'topic': topic, 'form': form}
	return render(request, 'froggy/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404
	if request.method != 'POST':
		form = EntryForm(instance=entry)
	else:
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('froggy:topic', args=[topic.id]))

	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'froggy/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('froggy:home'))

def register(request):
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		form = UserCreationForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('froggy:home'))
	context = {'form': form}
	return render(request, 'users/register.html', context)

froggy/templates/froggy/base.html
<style>
	#pad {
	padding-top: 25px;
	padding-bottom: 25px;
	padding-right: 50px;
	padding-left: 50px;
    background: url('http://bgrounds.ru/_include/img/bgs/yellow-fabric.jpg');
}
</style>

<nav class="navbar navbar-default">
  <div class="container-fluid">
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-content">
	  	<span class="icon-bar"></span>
	  	<span class="icon-bar"></span>
	  	<span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="{% url 'froggy:home' %}">FrogBlog</a>
	</div>
	<div class="collapse navbar-collapse" id="nav-content">
		<ul class="nav navbar-nav">
	  	  <li class="active"><a href="{% url 'froggy:topics' %}">Темы</a></li>
	  	  {% if user.is_authenticated %}
	  	  <li class="navbar-brand">
	  	  	<p>Привет, {{ user.username }}!</p>
	  	  </li>
	  	  <li class="active">
	  	  	  <a href="{% url 'users:logout' %}">выйти</a>
	  	  </li>
	  	  {% else %}
	  	  <li class="active">
	  	  	  <a href="{% url 'users:register' %}">регистрация</a>
	  	  </li>
	  	  <li class="active">
	  	  	  <a href="{% url 'users:login' %}">войти</a>
	  	  </li>
	  	  {% endif %}
	  	</ul>
	</div>
  </div>
</nav>

{% block content %}{% endblock content %}

froggy/templates/froggy/edit_entry.html
<!DOCTYPE html>
{% extends "froggy/base.html" %}
{% block content %}
{% load staticfiles %}
{% load bootstrap3 %}
<html>
<head>
	<title>Новый пост</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}	
</head>
<body id="pad">

	<p><a href="{% url 'froggy:topic' topic.id %}">{{ topic }}</a></p>

	<p>Редактирование:</p>
	<form action="{% url 'froggy:edit_entry' entry.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit" class="btn btn-primary">Сохранить изменения</button>
	</form>

</body>
</html>
{% endblock content %}

froggy/templates/froggy/home.html
<!DOCTYPE html>
{% extends "froggy/base.html" %}
{% block content %}
{% load staticfiles %}
{% load bootstrap3 %}
<style type="text/css">
	@import url('https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic');
	#txt {
		font-family: Lobster;
		color: maroon;
		font-size: 31px;
	}
</style>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" media="screen">
	<title>FrogBlog - Home</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}
</head>
<body id="pad">

	<div background="http://bgrounds.ru/_include/img/bgs/scratch-lines/fawn-scratch-lines.png">
	<div class="col-lg-6 col-lg-offset-6" id="txt">
		<h1>Let's begin FrogBlog!</h1>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-2">
				<img src="{% static "frog1.png" %}" width='300px'>
			</div>
		</div>
	</div>
	</div>

</body>
</html>
{% endblock content %}

froggy/templates/froggy/new_entry.html
<!DOCTYPE html>
{% extends "froggy/base.html" %}
{% block content %}
{% load staticfiles %}
{% load bootstrap3 %}
<html>
<head>
	<title>Новый пост</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}	
</head>
<body id="pad">

	<p><a href="{% url 'froggy:topic' topic.id %}">{{ topic }}</a></p>

	<p>Новый пост:</p>
	<form action="{% url 'froggy:new_entry' topic.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit" class="btn btn-primary">Опубликовать</button>
	</form>

</body>
</html>
{% endblock content %}

froggy/templates/froggy/new_topic.html
<!DOCTYPE html>
{% extends "froggy/base.html" %}
{% block content %}
{% load staticfiles %}
{% load bootstrap3 %}
<html>
<head>
	<title>Новая тема</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}	
</head>
<body id="pad">

	<p>Название темы:</p>
	<form action="{% url 'froggy:new_topic' %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit" class="btn btn-primary">Создать</button>
	</form>

</body>
</html>
{% endblock content %}

froggy/templates/froggy/topic.html
<!DOCTYPE html>
{% extends "froggy/base.html" %}
{% block content %}
{% load staticfiles %}
{% load bootstrap3 %}
<style type="text/css">
	@import url('https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic');
	@import url('https://fonts.googleapis.com/css?family=Alegreya');
	@import url('https://fonts.googleapis.com/css?family=Neucha');
	#txt {
		font-family: Neucha, cursive;
		color: navy;
		font-size: 19px;
	}
</style>
<html>
<head>
	<title>Тема: {{ topic }}</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}
</head>
<body id="pad">

	<div id="txt">
	<p style="font-family: Lobster; color: maroon; font-size: 27px;">{{ topic }}</p>

	<p>
		<a href="{% url 'froggy:new_entry' topic.id %}">Новый пост</a>
	</p>
				
	<ul>
	{% for entry in entries %}
	  <li>
	  	<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
	  	<p>{{ entry.text|linebreaks }}</p>
	  	<p>
	  	  <a href="{% url 'froggy:edit_entry' entry.id %}">Редактировать</a>
	  	</p>
	  </li>
	{% empty %}
	  <li>
	  	Пока здесь ничего нет...
	  </li>
	{% endfor %}
	</ul>
	</div>
</body>
</html>		

{% endblock content %}

froggy/templates/froggy/topics.html
<!DOCTYPE html>
{% extends "froggy/base.html" %}
{% block content %}
{% load staticfiles %}
{% load bootstrap3 %}
<style type="text/css">
	@import url('https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic');
	#txtx {
		font-family: Lobster;
		color: navy;
		font-size: 19px;
	}
</style>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" media="screen">
	<title>FrogBlog - Topics</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}
</head>
<body id="pad">

	<p>
	<div class="media" id="txtx">
		<a class="pull-left" href="#">
			<img class="media-object" width="150" src="{% static "frog2.jpg" %}">
		</a>
		<div class="media-body">
			<h2 class="media-heading">Темы</h2>
			<div>
				<ul>
				  	{% for topic in topics %}
		  				<li>
		  				  <a href="{% url 'froggy:topic' topic.id %}">{{ topic }}</a>
		  				</li>
					{% empty %}
		  				<li>Здесь еще нет тем...</li>
					{% endfor %}
				</ul>
				<a href="{% url 'froggy:new_topic' %}">Создать новую тему</a>
			</div>
		</div>
	</div>
	</p>

</body>
</html>
{% endblock content %}

users/templates/users/login.html
{% extends "froggy/base.html" %}
{% block content %}

	<!DOCTYPE html>
	{% load staticfiles %}
	{% load bootstrap3 %}
	<html>
	<head>
		<title>login</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}
	</head>
	<body id="pad">

		{% if form.errors %}
		<p>Your username and password didn't match. Please try again.</p>
		{% endif %}

		<form method="post" action="{% url 'users:login' %}">
			{% csrf_token %}
			{{ form.as_p }}

			<button name="submit" class="btn btn-primary">log in</button>
			<input type="hidden" name="next" value="{% url 'froggy:home' %}">
		</form>
	
	</body>
	</html>

{% endblock content %}

users/templates/users/register.html
{% extends "froggy/base.html" %}

{% block content %}

	<!DOCTYPE html>
	{% load staticfiles %}
	{% load bootstrap3 %}
	<html>
	<head>
		<title>registration</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}
	</head>
	<body id="pad">

		<form method="post" action="{% url 'users:register' %}">
			{% csrf_token %}
			{{ form.as_p }}

			<button name="submit" class="btn btn-primary">register</button>
			<input type="hidden" name="next" value="{% url 'froggy:home' %}">
		</form>
	
	</body>
	</html>

{% endblock content %}